Modify dependency installation in release workflow
Removed installation of dependencies and added commands to check loop and squashfs modules.

diff --git a/.github/workflows/workflow-release-linux-arm64.yml b/.github/workflows/workflow-release-linux-arm64.yml
--- a/.github/workflows/workflow-release-linux-arm64.yml
+++ b/.github/workflows/workflow-release-linux-arm64.yml
@@ -41,13 +41,11 @@ jobs:
       
       - name: Install dependencies
         run: |
-          sudo apt update -qq
-          sudo apt install -y -qq flatpak-builder rpm 
-          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
-          sudo flatpak install flathub org.freedesktop.Sdk/aarch64/23.08 -y
-          sudo flatpak install flathub org.electronjs.Electron2.BaseApp/aarch64/23.08 -y
-          npm install -g cordova
-          npm install
+          uname -a
+          lsmod | egrep 'loop|squashfs' || true
+          sudo modprobe loop || echo "modprobe loop failed"
+          sudo modprobe squashfs || echo "modprobe squashfs failed"
+          ls -l /dev/loop* || true
       
       - name: Build packages
         run: |
